feat(Icons): add IconProvider, optimize rendering and fix icons
consta-design-system/icons pull request #1
Opened 2022-10-24 14:04 UTC by N1MBER

consta-design-system/uikit#2708

2022-10-24 19:29 UTC, gizeasy requested changes

2022-10-24 19:29 UTC, gizeasy commented on src/components/IconsProvider/IconsProvider.tsx
> +export const cnIcons = withPrefix('icons')('Icons');
Не совсем понял зачем, префикс добавлять только для ключей, они и так разные получаются

2022-10-24 19:29 UTC, gizeasy commented on src/components/IconsProvider/IconsProvider.tsx
> +      {props.children}
Проверь пожалуйста, происходит ли ререндера компоненте который в children, при изменении `icons`

2022-10-24 19:29 UTC, gizeasy commented on src/icons/Icon/__stories__/Icon.docs.mdx
> +import {
папку stories наверное можно крохнуть

2022-10-24 19:29 UTC, gizeasy commented on src/icons/createIcon/createIcon.tsx
> +        {!addIcon ? (
давай без `!` поменяй местами))

2022-10-24 19:29 UTC, gizeasy commented on src/components/IconsProvider/IconsProviderList/IconsProviderList.tsx
> +      <div className={cnIcons()}>
Давай иконки добавлять в портал, с возможностью впровайдере указать `object` где этот портал встраивать

2022-10-24 19:29 UTC, gizeasy commented on src/components/IconsProvider/IconsProviderList/IconsProviderList.tsx
> +            <svg key={cnIcons(key, { index })}>
индекс не надо включать в ключ иначе просто так рендер иконки происходит, оставь только `key` с ним явно быстрее будет

2022-10-29 08:26 UTC, N1MBER commented on src/components/IconsProvider/IconsProvider.tsx
> +      {props.children}
Ререндера нет

2022-10-31 11:46 UTC, gizeasy requested changes
<img width="277" alt="image" src="https://user-images.githubusercontent.com/13190808/199000525-312c1778-3e10-455b-981f-64fab39d8f29.png">

укажи свойства по умолчанию

2022-10-31 11:48 UTC, gizeasy requested changes
в документацию добавь про сборку иконок через webpack

2022-10-31 11:49 UTC, gizeasy requested changes
думаю стоит подробнее описать в чем заключается оптимизация рендеренга

2022-10-31 12:21 UTC, gizeasy requested changes
Сейчас рендр иконки происходит 3 раза, 
2 раза в самой иконке, и 1 раз в провайдере
надо подумать как оптимизовать процесс и рендрерит ее 1 раз и уже готовый рендер использовать в провайдере или если требуется в компоненте иконки

2022-11-01 10:25 UTC, gizeasy approved these changes

2022-11-02 12:58 UTC, merged