feat(LazyIcon): add LazyIcon and createLazyIcon
consta-design-system/icons pull request #28
Opened 2023-08-09 20:03 UTC by gizeasy

closes consta-design-system/uikit#3203

2023-08-09 22:43 UTC, BagenovA requested changes

2023-08-09 22:43 UTC, BagenovA commented on src/components/LazyIcon/__stand__/LazyIcon.dev.stand.mdx
> +Иконка с ленивой загрузкой. Построена на [`React.lazy`](https://react.dev/reference/react/lazy).
Может так: Иконка с отложенной (ленивой) загрузкой. Построена на [`React.lazy`](https://react.dev/reference/react/lazy). Особенность компонента состоит в том, что иконки не будут попадать в главный бандл, а подгрузятся по мере их появления на странице. Каждая иконка будет лежать в отдельном чанке.

2023-08-09 22:43 UTC, BagenovA commented on src/components/LazyIcon/__stand__/LazyIcon.dev.stand.mdx
> +Функция вернет иконку с ленивой загрузкой и с интерфейсом обчной иконки, для того чтобы моджно было встраивать иконку в другие компоненты кита.
Может так: Функция возвращает иконку с отложенной загрузкой и интерфейсом обычной, для вставки в другие компоненты кита.

2023-08-10 09:38 UTC, gizeasy commented on src/components/LazyIcon/__stand__/LazyIcon.dev.stand.mdx
> +Иконка с ленивой загрузкой. Построена на [`React.lazy`](https://react.dev/reference/react/lazy).
fix

2023-08-10 09:38 UTC, gizeasy commented on src/components/LazyIcon/__stand__/LazyIcon.dev.stand.mdx
> +Функция вернет иконку с ленивой загрузкой и с интерфейсом обчной иконки, для того чтобы моджно было встраивать иконку в другие компоненты кита.
fix

2023-08-10 09:54 UTC, merged

2023-08-10 09:55 UTC, N1MBER approved these changes